[project]
name = "schemepoc"
version = "0.1.0"
description = "Proof of concept for a compile time scheme compiler"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
  "clang-format==22.1.8",
  "cmake==4.4.0",
  "copier>=9.17.0",
  "gcovr>=8.6",
  "mbake==1.4.6",
  "ninja>=1.13",
  "pre-commit>=4.6.1",
  "shellcheck-py>=0.11.0.1"
]
